type User {
  id: ID!
  email: String!
  name: String!
  createdAt: Time!
  updatedAt: Time!
}

extend type Query {
  getUser(id: ID!): User!
}

type CreateUserPayload {
  user: User!
  idToken: String!
}

input CreateUserInput {
  name: String!
  email: String!
  password: String!
}

extend type Mutation {
  createUser(input: CreateUserInput): CreateUserPayload!
}
