version: "3"
services:
  user:
    container_name: user
    build:
      context: ./build/api
      target: dev
    env_file:
      - build/api/.env
    tty: true
    volumes:
      - .:/app
    depends_on:
      - user-db

  user-db:
    container_name: user_db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: user_db
      TZ: 'Asia/Tokyo'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./build/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - '4306:3306'

networks:
  default:
    name: user_net
