version: "3"
services:
  organization:
    container_name: organization
    build:
      context: ./build/api
      target: dev
    env_file:
      - build/api/.env
    tty: true
    volumes:
      - .:/app
    depends_on:
      - organization-db

  organization-db:
    container_name: organization_db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: organization_dev
      TZ: 'Asia/Tokyo'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./build/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - '5306:3306'

networks:
  default:
    name: grpc_example_net
